# Generated by Django 3.1.5 on 2021-11-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='photo',
            new_name='photo_title',
        ),
        migrations.AddField(
            model_name='post',
            name='photo_body1',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='post',
            name='photo_body2',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='post',
            name='photo_body3',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
