# Generated by Django 3.1.5 on 2021-12-03 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20211130_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableAffiliate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_affiliate', models.ImageField(blank=True, upload_to='images')),
                ('name_affiliate', models.TextField()),
                ('commission_affiliate', models.CharField(max_length=200)),
                ('website_affiliate', models.TextField()),
                ('category_affiliate', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
