# Generated by Django 3.1.5 on 2021-12-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tableaffiliate'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_links',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
