# Generated by Django 3.1.5 on 2021-12-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_post_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableaffiliate',
            name='category_affiliate',
            field=models.CharField(max_length=255),
        ),
    ]
