# Generated by Django 3.1.5 on 2021-12-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='conclusion',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
