# Generated by Django 3.1.5 on 2021-12-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20211207_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='conclusion',
            field=models.TextField(blank=True),
        ),
    ]
